
# Runs build and test
name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install Dependencies
      run: |
        npm i
    - name: Build
      run: |
        npm run build