# Runs build and test
name: Build and Publish

on:
  push:
    branches: [ main ]

env:
  ADOBE_API_KEY: ${{ secrets.ADOBE_API_KEY }}

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install Dependencies
      run: |
        npm i
    - name: Build
      run: |
        npm run build
      env:
        ADOBE_API_KEY: ${{ secrets.ADOBE_API_KEY }}
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _site # The folder the action should deploy.
      env:
        ADOBE_API_KEY: ${{ secrets.ADOBE_API_KEY }}